### DISCUSSION TITLE
Tutorial for GitHub Badges Using Gist

### DISCUSSION THREAD

**Discussion by kathlenemagnus** [sparcians/pegasus#178] [Show and tell]
I've added badges to the Atlas README to display the pass rates of the RISC-V arch and Tenstorrent test suites.

Steps:
1. Created a new [gist](https://gist.github.com/kathlenemagnus/257907f4095b77a22da35df05f543a4a)
2. With my personal GitHub account, created a new "personal access token" with Gists permissions called `GIST_TOKEN`.
3. Copied the new `GIST_TOKEN` to Atlas as a repository secret also called `GIST_TOKEN`.
4. Added a new [workflow ](https://github.com/sparcians/atlas/blob/main/.github/workflows/post-merge-regression.yml) that runs after a push to main. This workflow builds Atlas, runs the test suites and then updates the badges. The `GIST_TOKEN` provides access to the Gist server.
```
      # Generate GitHub Badges
      - name: Create RISC-V Arch Tests Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 257907f4095b77a22da35df05f543a4a
          filename: riscv-arch.json
          label: RISC-V ARCH
          message: ${{ env.RISCV_ARCH_PASS_RATE }}
          color: yellow

      # Generate GitHub Badges
      - name: Create Tenstorrent Tests Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 257907f4095b77a22da35df05f543a4a
          filename: tenstorrent.json
          label: TENSTORRENT
          message: ${{ env.TENSTORRENT_PASS_RATE }}
          color: yellow
```
5. Added the badges to the README:
```
![riscv-arch](https://img.shields.io/endpoint?url=https://gist.githubusercontent.com/kathlenemagnus/257907f4095b77a22da35df05f543a4a/raw/riscv-arch.json)
![tenstorrent](https://img.shields.io/endpoint?url=https://gist.githubusercontent.com/kathlenemagnus/257907f4095b77a22da35df05f543a4a/raw/tenstorrent.json)
```

Apparently, GitHub does not allow workflows that run in pull requests from a fork to access secrets so the pull request workflow will not be able to access the Gist server. These instructions will only work for a workflow that is triggered by the repo itself like the post-merge "push to main" workflow.

Resources:
- [Dynamic Badge Actions GH](https://github.com/Schneegans/dynamic-badges-action/?tab=readme-ov-file#configuration)
- [Create Badges with GitHub Actions!](https://schneegans.github.io/tutorials/2022/04/18/badges)
- https://github.com/Schneegans/dynamic-badges-action/issues/15
